#!/usr/bin/env python3
"""
build_exploration_video.py — turn one MSL "exploration" page into a narrated
60-90s explainer video (visuals + audio), with zero pip installs.

Pipeline (all building blocks ship with Windows + the repo's ffmpeg):
  1. Read a scene script:  explorations/_video/scenes/<slug>.json
  2. Per scene, render a 1920x1080 still:
       - type "slide": build an ops-console-styled HTML slide -> screenshot (Edge headless)
       - type "page" : screenshot the real exploration page (optionally at an #anchor)
  3. Synthesize narration WAV per scene via utils/powershell/tts_sapi.ps1 (Windows SAPI).
  4. Build a per-scene clip: ffmpeg loops the still with a slow Ken-Burns zoom,
     muxes the narration, fades in/out. Clip length = narration + tail.
  5. Concat clips -> explorations/_video/out/<slug>.mp4

Why this shape: the live JS instruments on each page do NOT paint in one-shot
headless capture (they draw in animation frames the screenshotter never runs),
so the diagrams are re-drawn as static SVG inside the slides, and only the
*static* page content (hero/prose) is screenshotted directly. See DEV-LOG.

Usage (run from anywhere; the script anchors to the repo root):
  python utils/python/build_exploration_video.py <slug> [--keep] [--browser edge|chrome]
  python utils/python/build_exploration_video.py liquidity-deflation-spiral

Rule 1: this file anchors to the repo root via Path(__file__).resolve().parents[2]
and never assumes the invocation directory.
"""

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SCENES_DIR = REPO / "explorations" / "_video" / "scenes"
OUT_DIR = REPO / "explorations" / "_video" / "out"
BUILD_ROOT = REPO / "explorations" / "_video" / "build"
TTS_PS1 = REPO / "utils" / "powershell" / "tts_sapi.ps1"

W, H, FPS = 1920, 1080, 30
TAIL = 0.4          # seconds of silence held after each narration line
MIN_SCENE = 2.5     # floor on scene length
DEFAULT_SPEED = 1.0  # narration tempo (ffmpeg atempo); >1 = faster

# Procedural ambient binaural-beats bed (generated by ffmpeg, no audio files).
# carrier = base tone (Hz); beat = L/R offset the brain hears as a beat (7.83 ≈ alpha/theta);
# gain = bed level mixed UNDER the narration (narration stays at full).
DEFAULT_MUSIC = {"carrier": 110.0, "beat": 7.83, "gain": 0.16}

# Piper (free local *neural* TTS) — optional, resolved from %LOCALAPPDATA%\piper
# so nothing machine-specific is hardcoded. Install: piper.exe + a <voice>.onnx(+.json)
# under PIPER_VOICES. Override with env PIPER_EXE / PIPER_VOICES.
_LOCAL = Path(os.environ.get("LOCALAPPDATA", os.path.expanduser("~")))
PIPER_DIR = _LOCAL / "piper"
PIPER_EXES = [os.environ.get("PIPER_EXE"),
              str(PIPER_DIR / "piper" / "piper.exe"),
              str(PIPER_DIR / "piper.exe"), "piper"]
PIPER_VOICES = Path(os.environ.get("PIPER_VOICES", str(PIPER_DIR / "voices")))

BROWSERS = {
    "edge": [
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    ],
    "chrome": [
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    ],
}


def find_browser(pref):
    order = [pref] + [b for b in BROWSERS if b != pref]
    for name in order:
        for p in BROWSERS[name]:
            if Path(p).exists():
                return p
    sys.exit("No Edge/Chrome found for headless rendering.")


def tool(name):
    """Resolve ffmpeg/ffprobe from PATH, else the repo's known install dir."""
    p = shutil.which(name)
    if p:
        return p
    cand = Path(r"C:\ffmpeg\bin") / (name + ".exe")
    if cand.exists():
        return str(cand)
    sys.exit(f"{name} not found on PATH or C:\\ffmpeg\\bin")


# --------------------------------------------------------------------------- #
# Authored diagrams (re-drawn from the live instruments, static SVG).         #
# --------------------------------------------------------------------------- #
def diagram_svg(key, c):
    """c = palette dict (accent/good/bad/pool)."""
    acc, good, bad, pool = c["accent"], c["good"], c["bad"], c["pool"]
    fog, ink, line = "#c4c9d8", "#0a0c12", "#2a3146"
    if key == "circulation":
        return f"""
<svg viewBox="0 0 1200 560" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <defs>
    <marker id="ad" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto">
      <path d="M0,0 L9,4.5 L0,9 z" fill="{acc}"/></marker>
    <marker id="bd" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto">
      <path d="M0,0 L9,4.5 L0,9 z" fill="{bad}"/></marker>
    <marker id="gd" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto">
      <path d="M0,0 L9,4.5 L0,9 z" fill="{good}"/></marker>
  </defs>
  <!-- nodes -->
  <g>
    <rect x="40"  y="40"  width="240" height="92" rx="12" fill="{ink}" stroke="{acc}" stroke-width="2"/>
    <text x="160" y="78"  fill="{acc}" font-size="22" font-weight="700" text-anchor="middle">WAR-BOND</text>
    <text x="160" y="106" fill="{fog}" font-size="15" text-anchor="middle">the only source</text>

    <rect x="470" y="40"  width="260" height="92" rx="12" fill="{ink}" stroke="{pool}" stroke-width="2"/>
    <text x="600" y="78"  fill="{pool}" font-size="22" font-weight="700" text-anchor="middle">TREASURY</text>
    <text x="600" y="106" fill="{fog}" font-size="15" text-anchor="middle">where money pools</text>

    <rect x="470" y="380" width="260" height="92" rx="12" fill="{ink}" stroke="{good}" stroke-width="2"/>
    <text x="600" y="418" fill="{good}" font-size="22" font-weight="700" text-anchor="middle">STATION TILLS</text>
    <text x="600" y="446" fill="{fog}" font-size="15" text-anchor="middle">pay your contracts</text>

    <rect x="910" y="40"  width="250" height="92" rx="12" fill="{ink}" stroke="{acc}" stroke-width="2"/>
    <text x="1035" y="78" fill="{acc}" font-size="22" font-weight="700" text-anchor="middle">YOUR WALLET</text>
    <text x="1035" y="106" fill="{fog}" font-size="15" text-anchor="middle">you earn here</text>

    <rect x="910" y="380" width="250" height="92" rx="12" fill="{ink}" stroke="{bad}" stroke-width="2"/>
    <text x="1035" y="418" fill="{bad}" font-size="22" font-weight="700" text-anchor="middle">THE FRONT</text>
    <text x="1035" y="446" fill="{fog}" font-size="15" text-anchor="middle">buys output</text>
  </g>
  <!-- flows -->
  <line x1="280" y1="86" x2="462" y2="86" stroke="{acc}" stroke-width="3" marker-end="url(#ad)"/>
  <text x="372" y="74" fill="{acc}" font-size="14" text-anchor="middle">1 mint</text>

  <line x1="730" y1="86" x2="902" y2="86" stroke="{acc}" stroke-width="3" marker-end="url(#ad)"/>
  <text x="816" y="74" fill="{acc}" font-size="14" text-anchor="middle">2 bounties</text>

  <line x1="1035" y1="132" x2="1035" y2="374" stroke="{fog}" stroke-width="3" marker-end="url(#ad)" opacity="0.7"/>
  <text x="1120" y="256" fill="{fog}" font-size="14" text-anchor="middle">3 trade</text>
  <line x1="900" y1="430" x2="732" y2="430" stroke="{fog}" stroke-width="3" marker-end="url(#ad)" opacity="0.7"/>

  <path d="M600,374 C600,300 600,220 600,138" fill="none" stroke="{good}" stroke-width="3" marker-end="url(#gd)" transform="translate(-70,0)"/>
  <text x="430" y="256" fill="{good}" font-size="14" text-anchor="middle">4 front pays</text>
  <text x="430" y="276" fill="{good}" font-size="14" text-anchor="middle">(pump down)</text>

  <path d="M660,374 C690,300 690,220 670,138" fill="none" stroke="{bad}" stroke-width="3" marker-end="url(#bd)"/>
  <text x="770" y="256" fill="{bad}" font-size="14" text-anchor="middle">5 carrying cost</text>
  <text x="770" y="276" fill="{bad}" font-size="14" text-anchor="middle">(leak up)</text>
</svg>"""
    if key == "phase":
        return f"""
<svg viewBox="0 0 1000 620" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <defs>
    <linearGradient id="g" x1="0" y1="1" x2="1" y2="0">
      <stop offset="0" stop-color="{bad}" stop-opacity="0.30"/>
      <stop offset="0.5" stop-color="{ink}" stop-opacity="0.05"/>
      <stop offset="1" stop-color="{good}" stop-opacity="0.30"/>
    </linearGradient>
  </defs>
  <rect x="120" y="60" width="760" height="460" fill="url(#g)" stroke="{line}" stroke-width="2"/>
  <!-- boundary -->
  <path d="M120,180 C360,300 560,360 880,470" fill="none" stroke="{fog}" stroke-width="3" stroke-dasharray="10 8"/>
  <!-- regions -->
  <text x="720" y="170" fill="{good}" font-size="30" font-weight="700" text-anchor="middle">HEALTHY</text>
  <text x="720" y="205" fill="{fog}" font-size="17" text-anchor="middle">money circulates</text>
  <text x="300" y="430" fill="{bad}" font-size="30" font-weight="700" text-anchor="middle">SPIRAL</text>
  <text x="300" y="465" fill="{fog}" font-size="17" text-anchor="middle">money pools, board goes quiet</text>
  <!-- operating dot -->
  <circle cx="810" cy="118" r="13" fill="{acc}" stroke="{ink}" stroke-width="3"/>
  <!-- axes -->
  <text x="500" y="575" fill="{acc}" font-size="19" text-anchor="middle">war-bond rate  (the source)  &#8594;</text>
  <text x="60" y="290" fill="{acc}" font-size="19" text-anchor="middle" transform="rotate(-90 60 290)">front-pays-tills  (circulation)  &#8594;</text>
</svg>"""
    if key == "payer_gap":
        cool = "#60a5fa"
        return f"""
<svg viewBox="0 0 1200 540" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <text x="60" y="70" fill="{fog}" font-size="26">bid = min( price &#215; qty ,  till )</text>
  <!-- market asks -->
  <text x="60" y="150" fill="{acc}" font-size="22">market asks  (price &#215; qty)</text>
  <rect x="60" y="168" width="1040" height="68" rx="8" fill="{acc}" opacity="0.85"/>
  <!-- till can afford -->
  <text x="60" y="290" fill="{cool}" font-size="22">till can afford</text>
  <rect x="60" y="308" width="560" height="68" rx="8" fill="{cool}" opacity="0.85"/>
  <line x1="620" y1="150" x2="620" y2="470" stroke="{fog}" stroke-width="2" stroke-dasharray="7 7"/>
  <!-- you're paid -->
  <text x="60" y="430" fill="{good}" font-size="22">you're paid  (the shorter one)</text>
  <rect x="60" y="448" width="560" height="68" rx="8" fill="{good}"/>
  <!-- the gap brace -->
  <rect x="620" y="168" width="480" height="68" rx="8" fill="none" stroke="{bad}" stroke-width="2" stroke-dasharray="6 6"/>
  <text x="860" y="138" fill="{bad}" font-size="20" text-anchor="middle">the bid sags into this gap</text>
</svg>"""
    if key == "hub_threshold":
        return f"""
<svg viewBox="0 0 1200 460" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <text x="60" y="90" fill="{fog}" font-size="24">feed the till past the notch &#8594; its bid ceiling lifts (22 &#8594; 30 cr)</text>
  <rect x="60" y="150" width="1080" height="90" rx="12" fill="{ink}" stroke="{line}" stroke-width="2"/>
  <rect x="60" y="150" width="720" height="90" rx="12" fill="{good}" opacity="0.55"/>
  <line x1="700" y1="120" x2="700" y2="270" stroke="{acc}" stroke-width="4"/>
  <text x="700" y="305" fill="{acc}" font-size="20" text-anchor="middle">hub threshold</text>
  <text x="380" y="205" fill="{fog}" font-size="22" text-anchor="middle">broke &#8594; fat (reversible)</text>
  <text x="60" y="400" fill="{bad}" font-size="20">stop feeding &#8594; upkeep bleeds it straight back down past the notch</text>
</svg>"""
    if key == "opening_book":
        cool = "#60a5fa"
        return f"""
<svg viewBox="0 0 1200 540" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <defs><marker id="rd" markerWidth="9" markerHeight="9" refX="7" refY="4.5" orient="auto">
    <path d="M0,0 L9,4.5 L0,9 z" fill="{acc}"/></marker></defs>
  <text x="60" y="70" fill="{cool}" font-size="22">SCRIPTED OPENING &#183; keyframes you can memorise</text>
  <line x1="60" y1="150" x2="640" y2="150" stroke="{cool}" stroke-width="5"/>
  <g fill="{cool}">
    <circle cx="120" cy="150" r="11"/><circle cx="260" cy="150" r="11"/>
    <circle cx="400" cy="150" r="11"/><circle cx="540" cy="150" r="11"/>
  </g>
  <!-- fork -->
  <circle cx="640" cy="150" r="16" fill="{acc}"/>
  <text x="640" y="120" fill="{acc}" font-size="20" text-anchor="middle">your choice</text>
  <path d="M656,150 C760,150 800,90 920,90" fill="none" stroke="{acc}" stroke-width="4" marker-end="url(#rd)"/>
  <path d="M656,150 C760,150 800,230 920,230" fill="none" stroke="{acc}" stroke-width="4" marker-end="url(#rd)"/>
  <text x="940" y="96"  fill="{good}" font-size="22">HOLD &#8594; cover it</text>
  <text x="940" y="236" fill="{bad}"  font-size="22">LET FALL &#8594; new op</text>
  <!-- endgame -->
  <text x="60" y="380" fill="{acc}" font-size="22">PURE-PRESSURE ENDGAME &#183; keyframes spent, recall is worthless</text>
  <rect x="60" y="410" width="1080" height="70" rx="10" fill="{acc}" opacity="0.18" stroke="{acc}" stroke-width="2"/>
  <text x="600" y="453" fill="{fog}" font-size="22" text-anchor="middle">the front advances on accumulated pressure alone</text>
</svg>"""
    if key == "fog_map":
        cells = ""
        observed = {0, 1, 2, 5, 6, 7, 11, 12}
        for i in range(18):
            cx = 80 + (i % 6) * 185
            cy = 130 + (i // 6) * 130
            if i in observed:
                cells += f'<rect x="{cx}" y="{cy}" width="150" height="100" rx="10" fill="{acc}" opacity="0.85"/>'
            else:
                cells += (f'<rect x="{cx}" y="{cy}" width="150" height="100" rx="10" fill="none" '
                          f'stroke="{line}" stroke-width="2" stroke-dasharray="8 7"/>'
                          f'<text x="{cx+75}" y="{cy+58}" fill="{fog}" font-size="18" text-anchor="middle">?</text>')
        return f"""
<svg viewBox="0 0 1200 560" xmlns="http://www.w3.org/2000/svg" font-family="ui-monospace,Consolas,monospace">
  <text x="80" y="70" fill="{fog}" font-size="24">the schedule is fully determined &#8212; you just haven't <tspan fill="{acc}">seen</tspan> it yet</text>
  {cells}
  <text x="80" y="540" fill="{acc}" font-size="22">unknown &#8800; random &#183; a fresh player's ignorance is missing knowledge</text>
</svg>"""
    return f'<svg viewBox="0 0 100 100"><text x="50" y="50" fill="{fog}">?</text></svg>'


# --------------------------------------------------------------------------- #
# Slide HTML (ops-console aesthetic, matches the exploration pages).          #
# --------------------------------------------------------------------------- #
def slide_html(scene, spec):
    c = {k: spec.get(k, d) for k, d in
         (("accent", "#f59e0b"), ("good", "#34d399"), ("bad", "#f87171"), ("pool", "#7c6cff"))}
    acc = c["accent"]
    kicker = scene.get("kicker", "")
    headline = scene.get("headline", "")
    layout = scene.get("layout", "statement")
    lineage = spec.get("lineage", "")

    body_html = ""
    if layout == "diagram":
        # a scene may carry raw inline SVG ("svg"), else name a built-in diagram ("diagram")
        svg = scene.get("svg") or diagram_svg(scene.get("diagram", ""), c)
        body_html = f'<div class="diagram">{svg}</div>'
    elif layout == "bullets":
        items = "".join(f"<li>{b}</li>" for b in scene.get("bullets", []))
        body_html = f'<ul class="bul">{items}</ul>'
    elif layout == "outro":
        body_html = f'<p class="lede out">{scene.get("body","")}</p>'
    else:  # statement
        body_html = f'<p class="lede">{scene.get("body","")}</p>'

    big = "outro" if layout == "outro" else ""
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><style>
:root{{--ink-950:#07080c;--ink-900:#0a0c12;--ink-850:#0e1018;--line:#2a3146;
--fog-100:#eef1f8;--fog-300:#c4c9d8;--fog-500:#767d93;--accent:{acc};
--accent-soft:color-mix(in oklab,var(--accent) 16%,transparent);color-scheme:dark}}
*{{box-sizing:border-box;margin:0;padding:0}}
html,body{{width:{W}px;height:{H}px;overflow:hidden}}
body{{background-color:var(--ink-950);color:var(--fog-100);
font-family:"Segoe UI",Inter,system-ui,sans-serif;
background-image:radial-gradient(70rem 44rem at 50% -12%,var(--accent-soft),transparent 60%),
linear-gradient(rgba(255,255,255,.022) 1px,transparent 1px),
linear-gradient(90deg,rgba(255,255,255,.022) 1px,transparent 1px);
background-size:100% 100%,52px 52px,52px 52px;
display:flex;flex-direction:column;justify-content:center;padding:96px 132px}}
.kicker{{font-family:ui-monospace,Consolas,monospace;font-size:24px;letter-spacing:.26em;
text-transform:uppercase;color:var(--accent);margin-bottom:26px}}
h1{{font-size:74px;line-height:1.05;letter-spacing:-.02em;font-weight:800;max-width:1500px}}
h1.outro{{font-size:108px;color:var(--accent)}}
.lede{{font-size:44px;line-height:1.42;color:var(--fog-300);margin-top:40px;max-width:1480px;font-weight:400}}
.lede.out{{font-size:34px;font-family:ui-monospace,Consolas,monospace;color:var(--fog-500);
letter-spacing:.04em;margin-top:34px}}
.lede em{{color:var(--fog-100);font-style:italic}} .lede strong{{color:var(--fog-100)}}
.bul{{list-style:none;margin-top:46px;max-width:1560px}}
.bul li{{font-size:40px;line-height:1.4;color:var(--fog-300);padding:22px 0 22px 46px;
border-bottom:1px solid var(--line);position:relative}}
.bul li:before{{content:"";position:absolute;left:0;top:34px;width:18px;height:18px;border-radius:50%;
background:var(--accent);box-shadow:0 0 14px var(--accent)}}
.bul li b{{color:var(--fog-100)}}
.diagram{{margin-top:30px;display:flex;justify-content:center}}
.diagram svg{{width:100%;max-height:760px}}
.foot{{position:absolute;left:132px;bottom:54px;font-family:ui-monospace,Consolas,monospace;
font-size:20px;letter-spacing:.16em;color:var(--fog-500);text-transform:uppercase}}
</style></head><body>
{f'<div class="kicker">{kicker}</div>' if kicker else ''}
<h1 class="{big}">{headline}</h1>
{body_html}
<div class="foot">{lineage}</div>
</body></html>"""


# --------------------------------------------------------------------------- #
# Render primitives                                                            #
# --------------------------------------------------------------------------- #
def shoot(browser, url, out_png, vw, vh):
    import os
    import tempfile
    profile = tempfile.mkdtemp(prefix="edge_vid_")
    args = [browser, "--headless=new", "--disable-gpu", "--no-sandbox",
            "--hide-scrollbars", "--force-device-scale-factor=1",
            "--run-all-compositor-stages-before-draw",
            f"--window-size={vw},{vh}", f"--user-data-dir={profile}",
            f"--screenshot={out_png}", url]
    subprocess.run(args, capture_output=True)
    shutil.rmtree(profile, ignore_errors=True)
    if not Path(out_png).exists():
        sys.exit(f"screenshot failed: {url}")


def file_url(p: Path, anchor=""):
    u = "file:///" + str(p).replace("\\", "/")
    return u + (("#" + anchor) if anchor else "")


def find_piper():
    for c in PIPER_EXES:
        if not c:
            continue
        if Path(c).exists():
            return c
        w = shutil.which(c)
        if w:
            return w
    sys.exit("Piper not found. Set PIPER_EXE or install piper.exe under %LOCALAPPDATA%\\piper.")


def synth(text, out_wav, backend, voice, rate):
    if backend == "piper":
        exe = find_piper()
        model = voice if voice.endswith(".onnx") else str(PIPER_VOICES / f"{voice}.onnx")
        if not Path(model).exists():
            sys.exit(f"Piper voice model not found: {model}")
        subprocess.run([exe, "-m", model, "-f", str(out_wav)],
                       input=text, text=True, capture_output=True, check=True)
    else:  # sapi
        subprocess.run(
            ["powershell", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(TTS_PS1),
             "-Text", text, "-Out", str(out_wav), "-Voice", voice, "-Rate", str(rate)],
            capture_output=True, check=True)
    if not out_wav.exists():
        sys.exit(f"tts ({backend}) failed for: {text[:40]}...")


def atempo_chain(speed):
    """ffmpeg atempo accepts 0.5..2.0 per stage; chain for larger factors."""
    if abs(speed - 1.0) < 1e-3:
        return None
    stages, s = [], speed
    while s > 2.0:
        stages.append("atempo=2.0")
        s /= 2.0
    while s < 0.5:
        stages.append("atempo=0.5")
        s /= 0.5
    stages.append(f"atempo={s:.4f}")
    return ",".join(stages)


def wav_seconds(ffprobe, wav):
    r = subprocess.run([ffprobe, "-v", "error", "-show_entries", "format=duration",
                        "-of", "default=nw=1:nk=1", str(wav)],
                       capture_output=True, text=True, check=True)
    return float(r.stdout.strip())


def make_clip(ffmpeg, png, wav, out_mp4, dur, idx, speed=1.0):
    frames = int(round(dur * FPS))
    # alternate gentle zoom direction so consecutive scenes don't feel identical
    if idx % 2 == 0:
        z = "min(zoom+0.00040,1.12)"
    else:
        z = "if(eq(on,0),1.12,max(zoom-0.00040,1.0))"
    vf = (
        f"scale=3840:2160:force_original_aspect_ratio=increase,crop=3840:2160,"
        f"zoompan=z='{z}':d={frames}:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
        f"s={W}x{H}:fps={FPS},"
        f"fade=t=in:st=0:d=0.4,fade=t=out:st={max(0,dur-0.4):.3f}:d=0.4,format=yuv420p"
    )
    tempo = atempo_chain(speed)
    af = (f"{tempo}," if tempo else "") + \
        f"apad,afade=t=in:st=0:d=0.25,afade=t=out:st={max(0,dur-0.4):.3f}:d=0.4"
    subprocess.run(
        [ffmpeg, "-y", "-loop", "1", "-framerate", str(FPS), "-t", f"{dur:.3f}", "-i", str(png),
         "-i", str(wav),
         "-filter_complex", f"[0:v]{vf}[v];[1:a]{af}[a]",
         "-map", "[v]", "-map", "[a]", "-t", f"{dur:.3f}",
         "-c:v", "libx264", "-preset", "medium", "-crf", "20", "-pix_fmt", "yuv420p",
         "-r", str(FPS), "-c:a", "aac", "-ar", "48000", "-b:a", "128k",
         str(out_mp4)],
        capture_output=True, check=True)


def add_music(ffmpeg, ffprobe, in_mp4, out_mp4, cfg):
    """Mix a procedural ambient binaural-beats bed under the narration of in_mp4."""
    dur = wav_seconds(ffprobe, in_mp4)  # ffprobe format=duration works on mp4 too
    fL = float(cfg["carrier"])
    fR = fL + float(cfg["beat"])
    drone = fL * 1.5  # a soft perfect-fifth drone, equal in both ears (keeps the binaural pair intact)
    g = float(cfg["gain"])
    fc = (
        f"[1:a][2:a]join=inputs=2:channel_layout=stereo[bin];"
        f"[3:a]aformat=channel_layouts=stereo[dr];"
        f"[bin]volume=0.5[binv];[dr]volume=0.18[drv];"
        f"[binv][drv]amix=inputs=2:normalize=0[bedmix];"
        f"[bedmix]tremolo=f=0.1:d=0.25,lowpass=f=700,aecho=0.8:0.7:60:0.3,"
        f"volume={g:.3f},afade=t=in:d=2,afade=t=out:st={max(0,dur-3):.2f}:d=3[bed];"
        f"[0:a]aformat=channel_layouts=stereo[narr];"
        f"[narr][bed]amix=inputs=2:normalize=0[a]"
    )
    subprocess.run(
        [ffmpeg, "-y", "-i", str(in_mp4),
         "-f", "lavfi", "-t", f"{dur:.3f}", "-i", f"sine=frequency={fL}:sample_rate=48000",
         "-f", "lavfi", "-t", f"{dur:.3f}", "-i", f"sine=frequency={fR}:sample_rate=48000",
         "-f", "lavfi", "-t", f"{dur:.3f}", "-i", f"sine=frequency={drone}:sample_rate=48000",
         "-filter_complex", fc, "-map", "0:v", "-map", "[a]",
         "-c:v", "copy", "-c:a", "aac", "-ar", "48000", "-b:a", "160k", str(out_mp4)],
        capture_output=True, check=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("slug")
    ap.add_argument("--browser", default="edge", choices=list(BROWSERS))
    ap.add_argument("--tts", choices=["sapi", "piper"], help="override the scene script's TTS backend")
    ap.add_argument("--speed", type=float, help="override narration tempo (atempo); >1 = faster")
    ap.add_argument("--no-music", action="store_true", help="disable the ambient binaural bed")
    ap.add_argument("--keep", action="store_true", help="keep the per-scene build dir")
    args = ap.parse_args()

    spec_path = SCENES_DIR / f"{args.slug}.json"
    if not spec_path.exists():
        sys.exit(f"no scene script: {spec_path}")
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    page = REPO / "explorations" / args.slug / "index.html"
    if not page.exists():
        sys.exit(f"no exploration page: {page}")

    browser = find_browser(args.browser)
    ffmpeg, ffprobe = tool("ffmpeg"), tool("ffprobe")
    backend = args.tts or spec.get("tts", "sapi")
    default_voice = "en_US-amy-medium" if backend == "piper" else "Microsoft Zira Desktop"
    voice = spec.get("voice", default_voice) if backend == spec.get("tts", "sapi") else default_voice
    rate = int(spec.get("rate", 0))
    speed = args.speed if args.speed else float(spec.get("speed", DEFAULT_SPEED))
    music = None
    if not args.no_music and spec.get("music") is not False:
        music = {**DEFAULT_MUSIC, **(spec.get("music") if isinstance(spec.get("music"), dict) else {})}

    bdir = BUILD_ROOT / args.slug
    if bdir.exists():
        shutil.rmtree(bdir, ignore_errors=True)
    bdir.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    clips = []
    total = 0.0
    for i, sc in enumerate(spec["scenes"]):
        sid = f"{i:02d}_{sc['id']}"
        png = bdir / f"{sid}.png"
        wav = bdir / f"{sid}.wav"
        clip = bdir / f"{sid}.mp4"

        if sc["type"] == "page":
            vw, vh = sc.get("viewport", [1280, 800])
            shoot(browser, file_url(page, sc.get("anchor", "")), str(png), vw, vh)
        else:
            html = bdir / f"{sid}.html"
            html.write_text(slide_html(sc, spec), encoding="utf-8")
            shoot(browser, file_url(html), str(png), W, H)

        synth(sc["narration"], wav, backend, voice, rate)
        dur = max(MIN_SCENE, wav_seconds(ffprobe, wav) / speed + TAIL)
        make_clip(ffmpeg, png, wav, clip, dur, i, speed)
        clips.append(clip)
        total += dur
        print(f"  scene {sid}: {dur:5.1f}s")

    listf = bdir / "concat.txt"
    listf.write_text("".join(f"file '{c.as_posix()}'\n" for c in clips), encoding="utf-8")
    out_mp4 = OUT_DIR / f"{args.slug}.mp4"
    if music:
        concat_mp4 = bdir / "_concat.mp4"
        subprocess.run([ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", str(listf),
                        "-c", "copy", str(concat_mp4)], capture_output=True, check=True)
        add_music(ffmpeg, ffprobe, concat_mp4, out_mp4, music)
    else:
        subprocess.run([ffmpeg, "-y", "-f", "concat", "-safe", "0", "-i", str(listf),
                        "-c", "copy", str(out_mp4)], capture_output=True, check=True)

    if not args.keep:
        shutil.rmtree(bdir, ignore_errors=True)
    bed = f"binaural {music['carrier']:.0f}/{music['carrier']+music['beat']:.0f}Hz" if music else "none"
    print(f"\nDONE  {out_mp4}   (~{total:.0f}s, {len(clips)} scenes, tts={backend}, speed={speed}, music={bed})")


if __name__ == "__main__":
    main()
